### ISSUE TITLE
[Fabric 1.20.1 - 1.4.1] Advanced Memory Card uncraftable

### ISSUE THREAD

**Issue by LazyDope** [LasmGratel/BetterP2P#15]
I just installed the mod, but the item doesn't seem to be craftable. EMI also doesn't show a recipe. Using the item seems to function, it's just that the recipe is missing.
![2024-07-22_21 01 55](https://github.com/user-attachments/assets/b330b10e-560e-4717-800f-5d6971219468)

**Comment by cplir-c** [comment]
This looks to be due to the recipe using the old mod ID for AE2: "appliedenergistics2" instead of "ae2":

[Recipe used in BetterP2P 1.20](https://github.com/LasmGratel/BetterP2P/blob/1.20/common/src/main/resources/assets/betterp2p/recipes/advanced_memory_card.json#L5)
[Mod ID for AE2 fabric 1.20.1](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/fabric/1.20.1/src/main/java/appeng/api/ids/AEConstants.java#L31)

**Comment by LazyDope** [comment]
Ah, seems like a fairly straightforward fix then.

**Comment by LasmGratel** [comment]
@cplir-c Thank you, but recipe folder is also wrong (should be in data/ instead of assets/)
I'll fix them in next version
