### ISSUE TITLE
Feature: Include other p2p tunnel addons

### ISSUE THREAD

**Issue by LCoolJT** [LasmGratel/BetterP2P#21]
Im using this modpack for Gregtech and was wondering if there was a way to include EUP2P tunnels.
Other p2ps:
- pattern p2p

**Comment by MoltonMontro** [comment]
I'd also be interested in seeing this! (Monifactory includes the **Modern AE2 Additions** mod, which introduces Pattern P2P tunnels, alongside Multi P2P tunnels.)

**Comment by LasmGratel** [comment]
Multi P2P Tunnels are **suck** and I don't want to provide support for it due to how this mod works: In the previous version of AE2 (1.12.2), P2Ps _can_ have multiple inputs but when you use a Memory Card you can't essentially bind two **Input** mode tunnels for a P2P for that Memory Card will assign a new frequency for it. BetterP2P respects this and can only have **one** input and multiple outputs, or else I have to completely rewrite the GUI logic.

Other will be added in the next version

**Comment by LasmGratel** [comment]
Pattern P2P tunnels is now supported in v1.5.0
